apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: o4d02v5sl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o4d02v5sl-go 
  name: o4d02v5sl-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: o4d02v5sl-go
    weight: 100 
