apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o4d02v5sl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o4d02v5sl-go 
  name: o4d02v5sl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: o4d02v5sl-go 
